# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ECADVLSI/Documents/Pacchu_437/Exp_3_EncoderPriority/Exp_3_Encoder83.cache/wt [current_project]
set_property parent.project_path C:/Users/ECADVLSI/Documents/Pacchu_437/Exp_3_EncoderPriority/Exp_3_Encoder83.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/ECADVLSI/Documents/Pacchu_437/Exp_3_EncoderPriority/Exp_3_Encoder83.srcs/sources_1/new/Encoder83.v
synth_design -top encoder83prio -part xc7vx485tffg1157-1
write_checkpoint -noxdef encoder83prio.dcp
catch { report_utilization -file encoder83prio_utilization_synth.rpt -pb encoder83prio_utilization_synth.pb }
